{{- if .Values.api.ingress.enabled -}}
{{- $networkingApiIsStable := eq (include "networking.apiVersion.isStable" .) "true" -}}
{{- $networkingApiSupportsIngressClassName := eq (include "networking.apiVersion.supportIngressClassName" .) "true" -}}
{{- $serviceName := include "brigade.api.fullname" . -}}
{{- $servicePort := .Values.api.service.externalPort -}}
{{- $paths := .Values.api.ingress.paths -}}
apiVersion: {{ template "networking.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $serviceName }}
  labels:
    app.kubernetes.io/name: {{ template "brigade.api.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.api.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if and (.Values.api.ingress.ingressClassName) ($networkingApiSupportsIngressClassName) }}
  ingressClassName: {{ .Values.api.ingress.ingressClassName }}
  {{- end }}
  rules:
    {{- range $host := .Values.api.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          {{- range $path := $paths }}
          {{- if $networkingApiIsStable }}
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
          {{- else }}
          - path: {{ $path }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
          {{- end }}
          {{- end -}}
    {{- end -}}
  {{- if .Values.api.ingress.tls }}
  tls:
{{ toYaml .Values.api.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
