{{ if .Values.controller.enabled }}{{ $fullname := include "brigade.ctrl.fullname" . }}
{{ $serviceAccount := default $fullname .Values.controller.serviceAccount.name }}
apiVersion: {{ template "deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/name: {{ $fullname }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    role: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $fullname }}
      app: {{ $fullname }}
      role: controller
  template:
    metadata:
    {{- if .Values.controller.podAnnotations }}
      annotations:
{{ toYaml .Values.controller.podAnnotations | indent 8}}
    {{- end }}
      labels:
        app.kubernetes.io/name: {{ $fullname }}
        app: {{ $fullname }}
        role: controller
    spec:
      serviceAccountName: {{ $serviceAccount }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.controller.registry }}/{{ .Values.controller.name }}:{{ default .Chart.AppVersion .Values.controller.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.controller.pullPolicy }}
        command:
        - /usr/bin/brigade-controller
        {{ if .Values.controller.workerResources }}
        args:
        {{ if .Values.controller.workerResources.requests }}
        - -worker-requests-cpu={{ default "" .Values.controller.workerResources.requests.cpu }}
        - -worker-requests-memory={{ default "" .Values.controller.workerResources.requests.memory }}
        {{- end }}
        {{ if .Values.controller.workerResources.limits }}
        - -worker-limits-cpu={{ default "" .Values.controller.workerResources.limits.cpu }}
        - -worker-limits-memory={{ default "" .Values.controller.workerResources.limits.memory }}
        {{- end }}
        {{- end }}
        env:
          - name: BRIGADE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: BRIGADE_WORKER_IMAGE
            value: "{{ .Values.worker.registry }}/{{ .Values.worker.name }}:{{ default .Chart.AppVersion .Values.worker.tag }}"
          - name: BRIGADE_WORKER_PULL_POLICY
            value: {{ default "IfNotPresent" .Values.worker.pullPolicy }}
          {{- if .Values.worker.command }}
          - name: BRIGADE_WORKER_COMMAND
            value: {{ .Values.worker.command | quote }}
          {{- end }}
          - name: BRIGADE_WORKER_SERVICE_ACCOUNT
            value: {{ default "brigade-worker" .Values.worker.serviceAccount.name }}
          {{- if .Values.worker.defaultBuildStorageClass }}
          - name: BRIGADE_DEFAULT_BUILD_STORAGE_CLASS
            value: {{ .Values.worker.defaultBuildStorageClass }}
          {{- end }}
          {{- if .Values.worker.defaultCacheStorageClass }}
          - name: BRIGADE_DEFAULT_CACHE_STORAGE_CLASS
            value: {{ .Values.worker.defaultCacheStorageClass }}
          {{- end }}
      {{ if .Values.privateRegistry }}imagePullSecrets:
        - name: {{.Values.privateRegistry}}{{ end }}
{{ end }}
