{{ if .Values.vacuum.enabled }}{{ $fullname := include "brigade.vacuum.fullname" .}}
{{ $serviceAccount := default "brigade-vacuum" .Values.vacuum.serviceAccount.name }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/name: {{ template "brigade.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    role: vacuum
spec:
  schedule: "{{ default "@hourly" .Values.vacuum.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.vacuum.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.vacuum.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ template "brigade.fullname" . }}
            role: vacuum
        spec:
          serviceAccountName: {{ $serviceAccount }}
          {{- if .Values.vacuum.affinity }}
          affinity:
{{ toYaml .Values.vacuum.affinity | indent 12}}
          {{ end }}
          containers:
          - name: {{ .Chart.Name }}-vacuum
            image: "{{ .Values.vacuum.registry }}/{{ .Values.vacuum.name }}:{{ default .Chart.AppVersion .Values.vacuum.tag }}"
            imagePullPolicy: {{ default "IfNotPresent" .Values.vacuum.pullPolicy }}
            env:
            - name: VACUUM_AGE
              value: {{ default "" .Values.vacuum.age | quote }}
            - name: VACUUM_MAX_BUILDS
              value: {{ default "0" .Values.vacuum.maxBuilds | quote }}
            - name: VACUUM_SKIP_RUNNING_BUILDS
              value: {{ default "false" .Values.vacuum.skipRunningBuilds | quote }}
            - name: BRIGADE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          restartPolicy: OnFailure
{{ end }}
