{{ $fname := include "brigade.worker.fullname" . }}
{{ $serviceAccount := default "brigade-worker" .Values.worker.serviceAccount.name }}
{{ if .Values.worker.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount }}
  labels:
    app.kubernetes.io/name: {{ template "brigade.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
imagePullSecrets:
{{- range $imagePullSecret := .Values.worker.serviceAccount.imagePullSecrets }}
- name: {{ $imagePullSecret }}
{{- end }}
{{ if .Values.rbac.enabled }}
---
kind: Role
apiVersion: {{ template "brigade.rbac.version" }}
metadata:
  name: {{ $fname }}
  labels:
    app.kubernetes.io/name: {{ template "brigade.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "secrets", "persistentvolumeclaims", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: {{ template "brigade.rbac.version" }}
metadata:
  name: {{ $fname }}
  labels:
    app.kubernetes.io/name: {{ template "brigade.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
subjects:
- kind: ServiceAccount
  name: {{ $serviceAccount }}
roleRef:
  kind: Role
  name: {{ $fname }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
{{ end }}
