apiVersion: v1
kind: Secret
metadata:
  name: brigade-{{ sha256sum .Values.project| trunc 54 }}
  labels:
    app: brigade
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service }}
    component: project
  annotations:
    projectName: {{ .Values.project | quote }}
type: "brigade.sh/project"
stringData:
  repository: {{ .Values.repository | quote }}
  sharedSecret: {{ .Values.sharedSecret | quote }}
  cloneURL: {{ .Values.cloneURL | quote }}
  initGitSubmodules: {{ default "false" .Values.initGitSubmodules | quote }}
  {{ if .Values.defaultScriptName }}
  defaultScriptName: {{ .Values.defaultScriptName | quote }}
  {{- end }}
  {{ if .Values.defaultScript }}
  defaultScript: |
{{.Values.defaultScript | indent 4}}
  {{- end }}
  {{ if .Values.defaultConfigName }}
  defaultConfigName: {{ .Values.defaultConfigName | quote }}
  {{- end }}
  {{ if .Values.defaultConfig }}
  defaultConfig: |
{{.Values.defaultConfig | indent 4}}
  {{- end }}
  {{ if empty .Values.vcsSidecar }}
  vcsSidecar: {{ printf "brigadecore/git-sidecar:%s" .Chart.AppVersion }}
  {{- else if eq "NONE" .Values.vcsSidecar -}}
  {{- else }}
  vcsSidecar: {{ .Values.vcsSidecar | quote }}
  {{- end }}
  {{ if .Values.vcsSidecarResources }}
  vcsSidecarResources.limits.cpu: {{ default "" .Values.vcsSidecarResources.limits.cpu | quote }}
  vcsSidecarResources.limits.memory: {{ default "" .Values.vcsSidecarResources.limits.memory | quote }}
  vcsSidecarResources.requests.cpu: {{ default "" .Values.vcsSidecarResources.requests.cpu | quote }}
  vcsSidecarResources.requests.memory: {{ default "" .Values.vcsSidecarResources.requests.memory | quote }}
  {{- end }}
  {{ if .Values.buildStorageSize }}
  buildStorageSize: {{ .Values.buildStorageSize | quote }}
  {{- end }}
  {{ if .Values.imagePullSecrets }}
  imagePullSecrets: {{ .Values.imagePullSecrets | quote }}
  {{- end }}
  {{ if .Values.secrets }}
  secrets: '{{ .Values.secrets | toJson }}'
  {{- end }}
  {{ range $k, $v := .Values.github}}
  github.{{ $k }}: {{ $v | quote }}
  {{- end }}
  {{ range $k, $v := .Values.kubernetes }}
  kubernetes.{{ $k }}: {{ $v | quote }}
  {{- end }}
  {{ if .Values.sshKey }}
  sshKey: {{.Values.sshKey | replace "\n" "$" }}
  sshCert: {{ default "" .Values.sshCert | quote }}
  {{- end }}
  allowPrivilegedJobs: {{ default "true" .Values.allowPrivilegedJobs | quote }}
  {{ if .Values.allowHostMounts -}}
  allowHostMounts: {{ .Values.allowHostMounts | quote }}
  {{ else }}
  allowHostMounts: "false"
  {{- end }}
  {{ range $k, $v := .Values.worker -}}
  worker.{{ $k }}: {{ $v | quote }}
  {{ end -}}
  {{if .Values.workerCommand -}}
  workerCommand: {{.Values.workerCommand | quote }}
  {{- end }}
  {{if .Values.genericGatewaySecret -}}
  genericGatewaySecret: {{ .Values.genericGatewaySecret | quote }}
  {{- end }}
